name: ml_benchmark
channels:
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - snakemake=6.10.0
  - numpy=1.20.3
  - pandas=1.3.4
  - python=3.9.0
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - seaborn=0.9.0
  - plink=1.90b6.21
  - gemma=0.98.3
  - pyseer=1.3.9
  - bcftools=1.14
  - matplotlib=3.4.3
  - yaml=0.2.5
  - xgboost=1.5.0
  - lightgbm=3.2.1