sim: data/examples/results_BacGWASim_40_quant/sim.txt   #vcf/pickle
phen: data/examples/results_BacGWASim_40_quant/phen.txt    #phen/pickle
par: data/examples/results_BacGWASim_40_quant/par.txt
outDir: data/examples/results_BacGWASim_40_quant/ml_benchmark_res
phenRep: 10
method: ml    #'ml/gwas'
gwasModel: pyseer #pyseer/gemma
alpha: 1    #1(lasso)/0.0069(enet)
mlModel: lgbm       #lgbm/svc/lr/rf/xgb

#tools
python: ~/.local/easybuild/software/2017/Core/miniconda3/4.3.27/envs/MLBenchmarker/bin/python
cores: 32
